language: cpp

compiler:
  - gcc

matrix:
  include:
  - env: GCC_VERSION=7
    os: linux
    compiler: g++-7
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-7
          - lcov

before_script:
  - mkdir _build
  - cd _build
  - cmake ..

script:
  - cmake --build . && cmake --build . --target libmodules_coverage

after_success:
  # Uploading report to CodeCov
  - cd libmodules_coverage
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
