name: LibModules GitHub build

on:
  push:
    branches: master
  pull_request:
    branches: master

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Configure builder
      run: sudo apt-get install lcov

    - name: Checkout sources
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target libmodules_coverage

    - name: Deploy coverage logs
      working-directory: ${{github.workspace}}/build
      run: bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
